server:
  address: 0.0.0.0
  port: 443  # Порт для HTTPS
  ssl:
    key-store: /root/suitcase-app/keystore.p12
    key-store-password: changeit  # Замените на пароль вашего .p12 файла
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  application:
    name: suitcase-gateway
  boot:
    admin:
      client:
        url: https://bikeboxgo.ru:8085  # Адрес сервера SBA через HTTPS
        instance:
          name: suitcase-gateway  # Уникальное имя для каждого сервиса
  cloud:
    gateway:
      routes:
        - id: suitcase-booking
          uri: https://103.74.93.74:8443  # HTTPS для целевого сервиса
          predicates:
            - Path=/booking/**

        - id: suitcase-booking
          uri: https://103.74.93.74:8443  # HTTPS для целевого сервиса
          predicates:
            - Path=/availability/**

        - id: suitcase-booking
          uri: https://103.74.93.74:8443  # HTTPS для целевого сервиса
          predicates:
            - Path=/dashboard/**

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus  # открываем нужные эндпоинты
  metrics:
    tags:
      application: suitcase-gateway  # (опционально) добавляет теги для метрик
