spring:
  boot:
    admin:
      context-path: /admin
  application:
    name: suitcase-gateway

  cloud:
    gateway:
      routes:
        - id: suitcase-booking
          uri: http://103.74.93.74:8081
          predicates:
            - Path=/booking/**

        - id: suitcase-booking
          uri: http://103.74.93.74:8081
          predicates:
            - Path=/availability/**


  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: your-client-id
            client-secret: your-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/keycloak"  # ???????? ???????? ?? ???? URL
            scope: openid
            authorization-uri: http://localhost:8282/realms/suitcase/protocol/openid-connect/auth
            token-uri: http://localhost:8282/realms/suitcase/protocol/openid-connect/token
            user-info-uri: http://localhost:8282/realms/suitcase/protocol/openid-connect/userinfo
        provider:
          keycloak:
            issuer-uri: http://localhost:8282/realms/suitcase

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
server:
  address: 0.0.0.0
  port: 80