spring:
  application:
    name: suitcase-gateway
  boot:
    admin:
      client:
        url: http://bikeboxgo.ru  # Адрес сервера SBA
        instance:
          name: suitcase-gateway  # Уникальное имя для каждого сервиса!
  cloud:
    gateway:
      routes:
        - id: suitcase-booking
          uri: http://103.74.93.74:8081
          predicates:
            - Path=/booking/**

        - id: suitcase-booking
          uri: http://103.74.93.74:8081
          predicates:
            - Path=/availability/**

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
server:
  address: 0.0.0.0
  port: 80

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, loggers
  endpoint:
    health:
      show-details: always