server:
  address: 0.0.0.0
  port: 443  # Порт для HTTPS
  ssl:
    key-store: /app/keystore.p12
    key-store-password: changeit  # Замените на пароль вашего .p12 файла
    key-store-type: PKCS12
    key-alias: tomcat
    enabled: true

spring:
  application:
    name: suitcase-gateway
  boot:
    admin:
      client:
        url: http://bikeboxgo.ru:8085  # Адрес сервера SBA
        instance:
          name: suitcase-gateway  # Уникальное имя для каждого сервиса!

  cloud:
    gateway:
      routes:
        - id: suitcase-booking
          uri: http://suitcase-booking-container:8081  # Внутренний адрес контейнера
          predicates:
            - Path=/booking/**

        - id: suitcase-booking
          uri: http://suitcase-booking-container:8081  # Внутренний адрес контейнера
          predicates:
            - Path=/availability/**

        - id: suitcase-booking
          uri: http://suitcase-booking-container:8081  # Внутренний адрес контейнера
          predicates:
            - Path=/dashboard/**

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: "*"
