name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Check if SSH_PASSWORD is correctly loaded
        run: |
          echo "SSH Password: $SSH_PASSWORD"  # Печать пароля в консоль для проверки
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

      - name: Set up SSH password authentication and deploy
        run: |
          echo "$SSH_PASSWORD" | sshpass ssh -o StrictHostKeyChecking=no root@103.74.93.74 "echo 'SSH connection successful!' && cd /path/to/your/project && git pull origin main"
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}