name: Build and Deploy Gateway

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      # Шаг 1: Копируем JAR файл на удаленный сервер
      - name: Copy JAR to remote server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "build/libs/suitcase-gateway-0.0.1-SNAPSHOT.jar"
          target: "/root/suitcase-app/gateway"

      # Шаг 2: Копируем Dockerfile на удаленный сервер
      - name: Copy Dockerfile to remote server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "Dockerfile"
          target: "/root/suitcase-app/gateway"

      # Шаг 3: Создаем Docker-сеть
      - name: Create Docker Network
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Создаем Docker-сеть (если она еще не существует)
            docker network create suitcase-network || true

      # Шаг 4: Выполняем SSH-команды для сборки и запуска контейнера
      - name: SSH Command to Build and Run Docker Container
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /root/suitcase-app/gateway

            # Остановить и удалить старый контейнер, если он существует
            docker stop suitcase-gateway-container || true
            docker rm suitcase-gateway-container || true

            # Построить новый образ
            docker build -t suitcase-gateway .

            # Запустить новый контейнер и подключить его к сети
            docker run -d -p 443:443 -p 80:80 --name suitcase-gateway-container --network suitcase-network suitcase-gateway
